# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0004_capitalizeverbose'),
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('home', '0011_recipeitem_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('about_h1', models.CharField(blank=True, max_length=255)),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, verbose_name='Client URL')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageIntroItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('embed_url', models.URLField(blank=True, verbose_name='Embed URL')),
                ('intro_h1', models.CharField(blank=True, max_length=255)),
                ('intro_h2', models.CharField(blank=True, max_length=255)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_items', to='home.HomePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('service_h1', models.CharField(blank=True, max_length=255)),
                ('service_h2', models.CharField(blank=True, max_length=255)),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('skill_name', models.CharField(blank=True, max_length=255)),
                ('percent', models.PositiveSmallIntegerField(blank=True)),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('general_description', wagtail.wagtailcore.fields.RichTextField()),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, verbose_name='work URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='advantageitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepageadvantageitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepageadvantageitem',
            name='productitem_ptr',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='homepageproductitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepageproductitem',
            name='productitem_ptr',
        ),
        migrations.RemoveField(
            model_name='homepagerecipeitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagerecipeitem',
            name='recipeitem_ptr',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='image',
        ),
        migrations.RenameField(
            model_name='testimonialitem',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='testimonialitem',
            old_name='description',
            new_name='general_description',
        ),
        migrations.RenameField(
            model_name='testimonialitem',
            old_name='caption',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='homepageserviceitem',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='homepageserviceitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepageserviceitem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='homepageserviceitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='homepageserviceitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepageserviceitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepageserviceitem',
            name='link_external',
        ),
        migrations.RemoveField(
            model_name='homepageserviceitem',
            name='link_page',
        ),
        migrations.AddField(
            model_name='testimonialitem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testimonialitem',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testimonialitem',
            name='testimonial',
            field=wagtail.wagtailcore.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HomePageAboutItem',
            fields=[
                ('aboutitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.AboutItem')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_items', to='home.HomePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('home.aboutitem', models.Model),
        ),
        migrations.CreateModel(
            name='HomePageClientItem',
            fields=[
                ('clientitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.ClientItem')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_items', to='home.HomePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('home.clientitem', models.Model),
        ),
        migrations.CreateModel(
            name='HomePageWorkItem',
            fields=[
                ('workitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.WorkItem')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='home.HomePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('home.workitem', models.Model),
        ),
        migrations.DeleteModel(
            name='AdvantageItem',
        ),
        migrations.DeleteModel(
            name='HomePageAdvantageItem',
        ),
        migrations.DeleteModel(
            name='HomePageCarouselItem',
        ),
        migrations.DeleteModel(
            name='HomePageProductItem',
        ),
        migrations.DeleteModel(
            name='HomePageRecipeItem',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
        migrations.DeleteModel(
            name='RecipeItem',
        ),
        migrations.AddField(
            model_name='workitem',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='project_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='clientitem',
            name='client_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutitem',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutitem',
            name='scills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SkillItem'),
        ),
        migrations.AddField(
            model_name='homepageserviceitem',
            name='serviceitem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.ServiceItem'),
            preserve_default=False,
        ),
    ]
