# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20160715_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutitem',
            old_name='scills',
            new_name='skills',
        ),
    ]
