# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160715_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutitem',
            name='skills',
        ),
    ]
