# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_aboutitem_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutitem',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.SkillItem'),
            preserve_default=False,
        ),
    ]
