# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_aboutitem_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='link_external',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='link_page',
        ),
    ]
